// If no preperation is required, remove all content from here

==== Specialized Knowledge

**** Before you deploy this Quick Start, we recommend that you become familiar with the following AWS services. (If you are new to AWS, see Getting Started with AWS.)

  ** AWS CloudFormation
  ** Amazon VPC
  ** Amazon EBS
  ** Amazon EC2
  ** Amazon ECR
  ** Amazon ECS
  ** Amazon EFS
  ** Amazon S3

==== Prepare your AWS account

**** You need to have a valid IAM user account to access and create AWS Elastic Container service(ECS) stack.

* The quickstart template will create all the necessary components required to
** Start and run Fargate containers as well as an EFS volume
** Two Elastic load balancers
** Minimum number of Eight (8) Elastic IPs 

==== Prepare your DNS (domain names) account

** The Quick Start requires you to have two sub-domains for which SSL certificates is required and should be uploaded to Amazon Certificate Manager (ACM) before launching the Quick Start. Domain name should be registered in your company's DNS servers.  
** Please note, SSL Certificate is only required for production deployment and not for the evaluation set-up.

==== Prepare for the deployment

** The quick start requires resources listed above. Once the stack starts running, it will start incurring cost to your aws account. 
