// Include any postdeployment steps here, such as steps necessary to test that the deployment was successful. If there are no postdeployment steps, leave this file empty.

== Postdeployment steps
To test the system properly, the system requires to have a valid DNS entry pointing to the server's network load balancer's(NLB) ARN and also the NLB have SSL certificates and Elastic IPs attached to it.

Update your DNS and add two entries. One each for the web tier and video call tier. Take the ARNs of the network load balancers and add the appropriate entry in your DNS server.

After the DNS propagation, the servers will be accessible via https://<The domain name entered by you in the template>/. in a browser
The browser will show a login page and you can test the login using username "jsnow" and password "jsnow".  You will be able to change/disable the test user accounts via the identity management system included in the stack.

=== Test the Deployment

When the AWS Cloudformation template successfully creates the stack, the Fargate instance will be running in your AWS cluster, and the Cloudmeet application will be installed on the Amazon ECS host instances.

==== Evaluation
To verify that the Cloudmeet application is running and accessible, please follow the below steps:
1. In the AWS CloudFormation console, choose the Outputs tab from *Service Stack*, please capture the *VALUE* of corrosponding *KEY* attributes

** KEY Attribute1 - RCHATEVALNLBURL
** KEY Attribute2 - JVBEVALNLBURL
** KEY Attribute3 - CloudmeetDomain
** KEY Attribute4 - CloudcallDomain

Please share the *VALUE* of above *KEY* attributes to support@progentys.com (Radaji to deceide)

Progentys support team will map the shared *values* of *key* attributes to provided domain name.
Once Progentys support team confirms the completion of mapping activity, customer can access the URL (https://cloudmeetdomain/cloudmeet) in a web browser.
The default username and password for the application are "jsnow" & "jsnow" respectively. (Radaji to deceide)

==== Production
To verify that the Cloudmeet application is running and accessible, please follow the below steps:
1. In the AWS CloudFormation console, choose the Outputs tab from *Service Stack*, please capture the *VALUE* of corrosponding *KEY* attributes

** KEY Attribute - CloudmeetDomain

Customer can access the URL (https://cloudmeetdomain/cloudmeet) in a web browser.
The default username and password for the application are "jsnow" & "jsnow" respectively. (Radaji to deceide)


== Security
Only port 22 is open at startup. You can restrict this port by providing an IP address or range of IP addresses for the AdminIngressLocation parameter. If you want to open
these ports to everyone, set the IP address to 0.0.0.0/0. However, this is not advised because it leaves your instances insecure.